services:
  node:
    build:
      context: ./result
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks: 
      - default
    depends_on:
      - postgres
    volumes:
      - result:/app/result
  python:
    build:
      context: ./vote
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
    networks:
      - default
  redis:
    image: redis:alpine
    networks:
      - default
    volumes:
      - redis_data:/data
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: postgres 
    volumes:
      - postgres_data:/var/lib/postgresql/data
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 5000:5000
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  redis_data:
  postgres_data:
  result: